package com.rafdi.vitechasia.blog;

/**
 * Build configuration constants.
 * This file serves as a fallback in case BuildConfig is not generated by Gradle.
 * In normal operation, this would be replaced by the auto-generated BuildConfig.
 */
public class BuildConfig {
    // Set to true for debug builds, false for release builds
    public static final boolean DEBUG = true;

    // API configuration - matches build.gradle.kts settings
    public static final boolean USE_FAKE_API = DEBUG;

    // Application configuration
    public static final String APPLICATION_ID = "com.rafdi.vitechasia.blog";
    public static final String BUILD_TYPE = DEBUG ? "debug" : "release";
    public static final String FLAVOR = "";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
}
